remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
title: My Documentation Site
search_enabled: true

# Set navigation order
nav_order: 1

# Add your navigation structure (optional override)
nav:
  - title: "Home"
    url: /
  - title: "About Me"
    url: /about
  - title: "Projects"
    url: /projects
  - title: "Contact"
    url: /contact

# Optional extras
color_scheme: light
logo: /assets/logo.png
search_enabled: true
